import React from "react";
import { render, screen, fireEvent } from "@testing-library/react";
import { expect, it } from "@jest/globals";
import "@testing-library/jest-dom/jest-globals";
import dayjs from "dayjs";
import { ParcelsTableRow } from "../parcelsTable/types";
import StyleManager from "@/app/themes";
import Localization from "@/app/Localization";
import { ActionModalProps } from "./ActionModals/GeneralActionModal";
import DayOverviewModal from "./ActionModals/DayOverviewModal";
import DeleteParcelModal from "./ActionModals/DeleteParcelModal";
import DriverOverviewModal from "./ActionModals/DriverOverviewModal";
import GenerateMapModal from "./ActionModals/GenerateMapModal";
import ShippingLabelModal from "./ActionModals/ShippingLabelModal";
import ShoppingListModal from "./ActionModals/ShoppingListModal";
import { UpdateParcelStatuses } from "./ActionAndStatusBar";
