/* eslint no-undef: 0 */
interface SnapletList {
    itemName: string;
    rowOrder: number;
    quantityFor1?: string;
    notesFor1?: string;
    quantityFor2?: string;
    notesFor2?: string;
    quantityFor3?: string;
    notesFor3?: string;
    quantityFor4?: string;
    notesFor4?: string;
    quantityFor5?: string;
    notesFor5?: string;
    quantityFor6?: string;
    notesFor6?: string;
    quantityFor7?: string;
    notesFor7?: string;
    quantityFor8?: string;
    notesFor8?: string;
    quantityFor9?: string;
    notesFor9?: string;
    quantityFor10?: string;
    notesFor10?: string;
}

interface SnapletListRequired {
    itemName: string;
    rowOrder: number;
    quantityFor1: string | undefined;
    notesFor1: string | null;
    quantityFor2: string | undefined;
    notesFor2: string | null;
    quantityFor3: string | undefined;
    notesFor3: string | null;
    quantityFor4: string | undefined;
    notesFor4: string | null;
    quantityFor5: string | undefined;
    notesFor5: string | null;
    quantityFor6: string | undefined;
    notesFor6: string | null;
    quantityFor7: string | undefined;
    notesFor7: string | null;
    quantityFor8: string | undefined;
    notesFor8: string | null;
    quantityFor9: string | undefined;
    notesFor9: string | null;
    quantityFor10: string | undefined;
    notesFor10: string | null;
}

const snapletListToRequired = (list: SnapletList): SnapletListRequired => {
    return {
        itemName: list.itemName,
        rowOrder: list.rowOrder,
        quantityFor1: list.quantityFor1 ?? undefined,
        notesFor1: list.notesFor1 ?? null,
        quantityFor2: list.quantityFor2 ?? undefined,
        notesFor2: list.notesFor2 ?? null,
        quantityFor3: list.quantityFor3 ?? undefined,
        notesFor3: list.notesFor3 ?? null,
        quantityFor4: list.quantityFor4 ?? undefined,
        notesFor4: list.notesFor4 ?? null,
        quantityFor5: list.quantityFor5 ?? undefined,
        notesFor5: list.notesFor5 ?? null,
        quantityFor6: list.quantityFor6 ?? undefined,
        notesFor6: list.notesFor6 ?? null,
        quantityFor7: list.quantityFor7 ?? undefined,
        notesFor7: list.notesFor7 ?? null,
        quantityFor8: list.quantityFor8 ?? undefined,
        notesFor8: list.notesFor8 ?? null,
        quantityFor9: list.quantityFor9 ?? undefined,
        notesFor9: list.notesFor9 ?? null,
        quantityFor10: list.quantityFor10 ?? undefined,
        notesFor10: list.notesFor10 ?? null,
    };
};

const listsSeed: SnapletList[] = [
    {
        itemName: "Fresh Fruit / Vegetables",
        rowOrder: 1,
        quantityFor1: "Mixture",
        quantityFor2: "Mixture",
        quantityFor3: "Mixture",
        quantityFor4: "Mixture",
        quantityFor5: "Mixture",
        quantityFor6: "Mixture",
        quantityFor7: "Mixture",
        quantityFor8: "Mixture",
        quantityFor9: "Mixture",
        quantityFor10: "Mixture",
    },

    {
        itemName: "Eggs",
        rowOrder: 2,
        quantityFor1: "4",
        notesFor1:
            "Please pack egg box into a packing box and not a bag to avoid potential humpty dumpties during delivery",
        quantityFor2: "6",
        notesFor2:
            "Please pack egg box into a packing box and not a bag to avoid potential humpty dumpties during delivery",
        quantityFor3: "6",
        notesFor3:
            "Please pack egg box into a packing box and not a bag to avoid potential humpty dumpties during delivery",
        quantityFor4: "6",
        notesFor4:
            "Please pack egg box into a packing box and not a bag to avoid potential humpty dumpties during delivery",
        quantityFor5: "6",
        notesFor5:
            "Please pack egg box into a packing box and not a bag to avoid potential humpty dumpties during delivery",
        quantityFor6: "6",
        notesFor6:
            "Please pack egg box into a packing box and not a bag to avoid potential humpty dumpties during delivery",
        quantityFor7: "10",
        notesFor7:
            "Please pack egg box into a packing box and not a bag to avoid potential humpty dumpties during delivery",
        quantityFor8: "10",
        notesFor8:
            "Please pack egg box into a packing box and not a bag to avoid potential humpty dumpties during delivery",
        quantityFor9: "12",
        notesFor9:
            "Please pack egg box into a packing box and not a bag to avoid potential humpty dumpties during delivery",
        quantityFor10: "12",
        notesFor10:
            "Please pack egg box into a packing box and not a bag to avoid potential humpty dumpties during delivery",
    },

    {
        itemName: "Washing Up Liquid",
        rowOrder: 3,
        quantityFor1: "1 decanted",
        notesFor1: "Please only use decanted rather than full",
        quantityFor2: "1 decanted",
        notesFor2: "Please only use decanted rather than full",
        quantityFor3: "1",
        quantityFor4: "1",
        quantityFor5: "1",
        quantityFor6: "1",
        quantityFor7: "1",
        quantityFor8: "1",
        quantityFor9: "1",
        quantityFor10: "1",
    },

    {
        itemName: "Laundry Pods",
        rowOrder: 4,
        quantityFor1: "1 bag of 2 pods",
        quantityFor2: "1 bag of 4 pods",
        quantityFor3: "1 bag of 4 pods",
        quantityFor4: "6 pods",
        notesFor4: "1 bag of 4 & 1 bag of 2",
        quantityFor5: "6 pods",
        notesFor5: "1 bag of 4 & 1 bag of 2",
        quantityFor6: "8 pods",
        notesFor6: "2 bags of 4 pods",
        quantityFor7: "8 pods",
        notesFor7: "2 bags of 4 pods",
        quantityFor8: "8 pods",
        notesFor8: "2 bags of 4 pods",
        quantityFor9: "8 pods",
        notesFor9: "2 bags of 4 pods",
        quantityFor10: "8 pods",
        notesFor10: "2 bags of 4 pods",
    },

    {
        itemName: "Nappies and Baby Wipes",
        rowOrder: 5,
        quantityFor2: "As Required",
        notesFor2: "Please ask if unsure",
        quantityFor3: "As Required",
        notesFor3: "Please ask if unsure",
        quantityFor4: "As Required",
        notesFor4: "Please ask if unsure",
        quantityFor5: "As Required",
        notesFor5: "Please ask if unsure",
        quantityFor6: "As Required",
        notesFor6: "Please ask if unsure",
        quantityFor7: "As Required",
        notesFor7: "Please ask if unsure",
        quantityFor8: "As Required",
        notesFor8: "Please ask if unsure",
        quantityFor9: "As Required",
        notesFor9: "Please ask if unsure",
        quantityFor10: "As Required",
        notesFor10: "Please ask if unsure",
    },

    {
        itemName: "Oats",
        rowOrder: 6,
        quantityFor2: "1 bag",
        quantityFor3: "1 bag",
        quantityFor4: "1 bag",
        quantityFor5: "1 bag",
        quantityFor6: "1 bag",
        quantityFor7: "1 bag",
        quantityFor8: "1 bag",
        quantityFor9: "1 bag",
        quantityFor10: "1 bag",
    },

    {
        itemName: "Bread",
        rowOrder: 7,
        quantityFor1: "1",
        notesFor1: "Not always in stock",
        quantityFor2: "1",
        notesFor2: "Not always in stock",
        quantityFor3: "1",
        notesFor3: "Not always in stock",
        quantityFor4: "2",
        notesFor4: "Not always in stock",
        quantityFor5: "2",
        notesFor5: "Not always in stock",
        quantityFor6: "2",
        notesFor6: "Not always in stock",
        quantityFor7: "3",
        notesFor7: "Not always in stock",
        quantityFor8: "3",
        notesFor8: "Not always in stock",
        quantityFor9: "3",
        notesFor9: "Not always in stock",
        quantityFor10: "3",
        notesFor10: "Not always in stock",
    },

    {
        itemName: "Pet Food Box (only if requested)",
        rowOrder: 8,
        quantityFor1: "pre-made box",
        quantityFor2: "pre-made box",
        quantityFor3: "pre-made box",
        quantityFor4: "pre-made box",
        quantityFor5: "pre-made box",
        quantityFor6: "pre-made box",
        quantityFor7: "pre-made box",
        quantityFor8: "pre-made box",
        quantityFor9: "pre-made box",
        quantityFor10: "pre-made box",
    },

    {
        itemName: "Cereal",
        rowOrder: 9,
        quantityFor1: "3 sachets or small box or 1 sleeve weetabix",
        quantityFor2: "1 small cereal",
        quantityFor3: "1 medium /large cereal",
        quantityFor4: "2 Medium boxes cereal",
        quantityFor5: "2 medium boxes cereal",
        quantityFor6: "1 large and 1 small cereal",
        quantityFor7: "1 large and 1 small cereal",
        quantityFor8: "2 large boxes cereals",
        quantityFor9: "2 large boxes cereal",
        quantityFor10: "2 large boxes cereal include one supersize if around.",
    },

    {
        itemName: "Tea / Coffee",
        rowOrder: 10,
        quantityFor1: "40 teabags/small jar",
        notesFor1: "if neither listed, give tea",
        quantityFor2: "80 teabags/small jar",
        notesFor2: "if neither listed, give tea",
        quantityFor3: "80 teabags/small jar",
        notesFor3: "if neither listed, give tea",
        quantityFor4: "80 teabags/medium jar",
        notesFor4: "if neither listed, give tea",
        quantityFor5: "80 teabags/medium jar",
        notesFor5: "if neither listed, give tea",
        quantityFor6: "80 teabags/medium jar",
        notesFor6: "if neither listed, give tea",
        quantityFor7: "80 teabags/large jar",
        notesFor7: "if neither listed, give tea",
        quantityFor8: "120 teabags/large jar",
        notesFor8: "if neither listed, give tea",
        quantityFor9: "120 teabags/large jar",
        notesFor9: "if neither listed, give tea",
        quantityFor10: "120 teabags/large jar",
        notesFor10: "if neither listed, give tea",
    },

    {
        itemName: "Milk",
        rowOrder: 11,
        quantityFor1: "1 Litre",
        notesFor1: "skimmed",
        quantityFor2: "1 Litre",
        notesFor2: "1 full fat",
        quantityFor3: "2",
        notesFor3: "1 Whole if Child",
        quantityFor4: "2",
        notesFor4: "1 Whole if Child",
        quantityFor5: "2",
        notesFor5: "1 Whole if Child",
        quantityFor6: "3",
        notesFor6: "2 full fat or skimmed",
        quantityFor7: "3",
        notesFor7: "2 full fat or skimmed",
        quantityFor8: "3",
        notesFor8: "2 full fat or skimmed",
        quantityFor9: "4",
        notesFor9: "3 full fat or skimmed",
        quantityFor10: "4",
        notesFor10: "3 full fat or skimmed",
    },

    {
        itemName: "Drinks (inc Fruit Juice)",
        rowOrder: 12,
        quantityFor1: "2 small cartons/tins",
        notesFor1: "1 litre fruit juice",
        quantityFor2: "1",
        notesFor2: "1 litre fruit juice",
        quantityFor3: "1",
        notesFor3: "1 litre fruit juice",
        quantityFor4: "1",
        notesFor4: "1 litre fruit juice",
        quantityFor5: "1",
        notesFor5: "1 litre fruit juice",
        quantityFor6: "1",
        notesFor6: "Fruit Juice",
        quantityFor7: "2",
        notesFor7: "Fruit Juice",
        quantityFor8: "2",
        notesFor8: "Fruit Juice",
        quantityFor9: "2",
        notesFor9: "Fruit Juice",
        quantityFor10: "2",
        notesFor10: "Fruit Juice",
    },

    {
        itemName: "Squash",
        rowOrder: 13,
        quantityFor5: "1",
        notesFor5: "1 standard bottle (if no squash use fruit juice)",
        quantityFor6: "1",
        notesFor6: "1 standard bottle (if no squash use fruit juice)",
        quantityFor7: "1",
        notesFor7: "1 standard bottle (if no squash use fruit juice)",
        quantityFor8: "1",
        notesFor8: "1 large bottle (if no squash use fruit juice)",
        quantityFor9: "1",
        notesFor9: "1 large bottle (if no squash use fruit juice)",
        quantityFor10: "1",
        notesFor10: "1 large bottle (if no squash use fruit juice)",
    },

    {
        itemName: "Soup - extra being added due to cold weather",
        rowOrder: 14,
        quantityFor1: "2",
        notesFor1: "Please don't divide cuppa soup boxes -- 1 box = 1 tin",
        quantityFor2: "4",
        quantityFor3: "6",
        quantityFor4: "8",
        quantityFor5: "8",
        quantityFor6: "8",
        quantityFor7: "8",
        quantityFor8: "10",
        quantityFor9: "10",
        quantityFor10: "10",
    },

    {
        itemName: "Other Tinned Vegetables - everyone to have carrots",
        rowOrder: 15,
        quantityFor1: "2",
        notesFor1: "use small tins if possible",
        quantityFor2: "2",
        quantityFor3: "3",
        notesFor3: "2 carrots",
        quantityFor4: "3",
        notesFor4: "2 carrots",
        quantityFor5: "3",
        notesFor5: "2 carrots",
        quantityFor6: "4",
        notesFor6: "3 carrots",
        quantityFor7: "4",
        notesFor7: "3 carrots",
        quantityFor8: "4",
        notesFor8: "3 carrots",
        quantityFor9: "5",
        notesFor9: "3 carrots",
        quantityFor10: "5",
        notesFor10: "3 carrots",
    },

    {
        itemName: "Pulses",
        rowOrder: 16,
        quantityFor1: "1",
        quantityFor2: "1",
        quantityFor3: "2",
        quantityFor4: "4",
        quantityFor5: "4",
        quantityFor6: "4",
        quantityFor7: "4",
        quantityFor8: "4",
        quantityFor9: "4",
        quantityFor10: "4",
    },

    {
        itemName: "Dried Pulses",
        rowOrder: 17,
        quantityFor5: "1 bag",
        quantityFor6: "1 bag",
        quantityFor7: "1 bag",
        quantityFor8: "1 bag",
        quantityFor9: "1 bag",
        quantityFor10: "1 bag",
    },

    {
        itemName: "Baked Beans / Tinned Spaghetti for Children",
        rowOrder: 18,
        quantityFor1: "1",
        quantityFor2: "2",
        quantityFor3: "3",
        quantityFor4: "4",
        quantityFor5: "5",
        quantityFor6: "6",
        quantityFor7: "7",
        quantityFor8: "8",
        quantityFor9: "9",
        quantityFor10: "10",
    },

    {
        itemName: "Tinned Tomatoes",
        rowOrder: 19,
        quantityFor1: "1",
        quantityFor2: "1",
        quantityFor3: "2",
        quantityFor4: "2",
        quantityFor5: "2",
        quantityFor6: "3",
        quantityFor7: "3",
        quantityFor8: "3",
        quantityFor9: "3",
        quantityFor10: "3",
    },

    {
        itemName: "Meat - If eat pork please include at least 50% pork based.",
        rowOrder: 20,
        quantityFor1: "3",
        notesFor1: "mix",
        quantityFor2: "3",
        notesFor2: "mix",
        quantityFor3: "4",
        notesFor3: "Mixture",
        quantityFor4: "5",
        notesFor4: "Mixture",
        quantityFor5: "6",
        notesFor5: "Mixture",
        quantityFor6: "6",
        notesFor6: "Mixture",
        quantityFor7: "7",
        notesFor7: "Mixture",
        quantityFor8: "7",
        notesFor8: "Mixture",
        quantityFor9: "8",
        notesFor9: "Mixture",
        quantityFor10: "8",
        notesFor10: "Mixture",
    },

    {
        itemName: "Fish",
        rowOrder: 21,
        quantityFor1: "2",
        quantityFor2: "3",
        quantityFor3: "3",
        quantityFor4: "4",
        quantityFor5: "4",
        quantityFor6: "5",
        quantityFor7: "5",
        quantityFor8: "6",
        quantityFor9: "6",
        quantityFor10: "7",
    },

    {
        itemName: "Vegetarian Meal",
        rowOrder: 22,
        quantityFor1: "1",
        notesFor1: "If client is veggie",
        quantityFor2: "2",
        notesFor2: "If client is veggie",
        quantityFor3: "2",
        notesFor3: "If client is veggie",
        quantityFor4: "3",
        notesFor4: "If client is veggie",
        quantityFor5: "4",
        notesFor5: "If client is veggie",
        quantityFor6: "5",
        notesFor6: "If client is veggie",
        quantityFor7: "5",
        notesFor7: "If client is veggie",
        quantityFor8: "6",
        notesFor8: "If client is veggie",
        quantityFor9: "6",
        notesFor9: "If client is veggie",
        quantityFor10: "6",
        notesFor10: "If client is veggie",
    },

    {
        itemName: "Cooking Sauce",
        rowOrder: 23,
        quantityFor1: "1",
        quantityFor2: "1",
        quantityFor3: "1",
        quantityFor4: "2",
        quantityFor5: "2",
        quantityFor6: "2",
        quantityFor7: "2",
        quantityFor8: "3",
        quantityFor9: "3",
        quantityFor10: "3",
    },

    {
        itemName: "Potatoes",
        rowOrder: 24,
        quantityFor1: "1",
        notesFor1: "Small tin or dried mash",
        quantityFor2: "1",
        notesFor2: "Big tin or dried mash",
        quantityFor3: "2",
        notesFor3: "Big tin and/or dried mash",
        quantityFor4: "2",
        notesFor4: "Big tin and/or dried mash",
        quantityFor5: "3",
        quantityFor6: "4",
        quantityFor7: "4",
        quantityFor8: "4",
        quantityFor9: "4",
        quantityFor10: "4",
    },

    {
        itemName: "Savoury Snacks",
        rowOrder: 25,
        quantityFor1: "1",
        quantityFor2: "2",
        quantityFor3: "2",
        quantityFor4: "2",
        quantityFor5: "3",
        quantityFor6: "3",
        quantityFor7: "4",
        quantityFor8: "4",
        quantityFor9: "4",
        quantityFor10: "4",
    },

    {
        itemName: "Custard",
        rowOrder: 26,
        quantityFor1: "1",
        quantityFor2: "1",
        quantityFor3: "1",
        quantityFor4: "1",
        quantityFor5: "2",
        quantityFor6: "2",
        quantityFor7: "2",
        quantityFor8: "2",
        quantityFor9: "2",
        quantityFor10: "2",
    },

    {
        itemName: "Oil - Families Only",
        rowOrder: 27,
        quantityFor4: "1",
        quantityFor5: "1",
        quantityFor6: "1",
        quantityFor7: "1",
        quantityFor8: "1",
        quantityFor9: "1",
        quantityFor10: "1",
    },

    {
        itemName: "Pasta",
        rowOrder: 28,
        quantityFor1: "1kg",
        quantityFor2: "1.5kg",
        quantityFor3: "2kg",
        quantityFor4: "2.5kg",
        quantityFor5: "2.5kg",
        quantityFor6: "2.5kg",
        quantityFor7: "3kg",
        quantityFor8: "3kg",
        quantityFor9: "3kg",
        quantityFor10: "4kg",
    },

    {
        itemName: "Rice",
        rowOrder: 29,
        quantityFor1: "1 Instant Rice Pouch",
        notesFor1: "or 1 small 500g bag",
        quantityFor2: "1kg",
        notesFor2:
            "Only if request in dietary info - please do not use 500 grm rice these are for singles only.",
        quantityFor3: "1kg",
        notesFor3: "Only if request in dietary info - please do not use 500grm rice bags",
        quantityFor4: "1kg",
        notesFor4: "Only if request in dietary info - please do not use 500grm rice bags",
        quantityFor5: "1kg",
        notesFor5: "Only if request in dietary info - please do not use 500grm rice bags",
        quantityFor6: "1kg",
        notesFor6:
            "Only if requested in dietary info, use big bag if available Please do not use 500grm bags",
        quantityFor7: "2kg",
        notesFor7: "Only if requested in dietary info, Please do not use 500 grm bags",
        quantityFor8: "2kg",
        notesFor8: "Only if requested in dietary info, Please do not use 500 grm bags",
        quantityFor9: "2kg plus",
        notesFor9: "Only if requested in dietary info, use big bag if available",
        quantityFor10: "2kg plus",
        notesFor10: "Only if requested in dietary info, use big bag if available",
    },

    {
        itemName: "Instant Noodles / Pasta for those with no cooking facilities",
        rowOrder: 30,
        quantityFor1: "2",
        notesFor1: "Only if no cooking facilities",
    },

    {
        itemName: "Rice Pudding",
        rowOrder: 31,
        quantityFor4: "1",
        quantityFor5: "2",
        quantityFor6: "2",
        quantityFor7: "2",
        quantityFor8: "2",
        quantityFor9: "2",
        quantityFor10: "2",
    },

    {
        itemName: "Other Pudding",
        rowOrder: 32,
        quantityFor1: "1",
        quantityFor2: "1",
        quantityFor3: "1",
        quantityFor4: "1",
        quantityFor5: "1",
        quantityFor6: "1",
        quantityFor7: "1",
        quantityFor8: "1",
        quantityFor9: "1",
        quantityFor10: "1",
    },

    {
        itemName: "Jam / Honey / Peanut Butter (Preserves)",
        rowOrder: 33,
        quantityFor1: "1",
        quantityFor2: "1",
        quantityFor3: "1",
        quantityFor4: "1",
        quantityFor5: "1",
        quantityFor6: "1",
        quantityFor7: "1",
        quantityFor8: "1",
        quantityFor9: "2",
        quantityFor10: "2",
    },

    {
        itemName: "Tinned Fruit",
        rowOrder: 34,
        quantityFor1: "1",
        quantityFor2: "1",
        quantityFor3: "2",
        notesFor3: "If very large tins please cut back",
        quantityFor4: "2",
        notesFor4: "If very large tins please cut back",
        quantityFor5: "3",
        notesFor5: "If very large tins please cut back",
        quantityFor6: "3",
        notesFor6: "If very large tins please cut back",
        quantityFor7: "3",
        notesFor7: "If very large tins please cut back",
        quantityFor8: "4",
        notesFor8: "If very large tins please cut back",
        quantityFor9: "4",
        notesFor9: "If very large tins please cut back",
        quantityFor10: "4",
        notesFor10: "If very large tins please cut back",
    },

    {
        itemName: "Cereal bars",
        rowOrder: 35,
        quantityFor1: "1",
        quantityFor2: "2",
        quantityFor3: "3",
        quantityFor4: "4",
        quantityFor5: "5",
        quantityFor6: "6",
        quantityFor7: "7",
        quantityFor8: "8",
        quantityFor9: "9",
        quantityFor10: "10",
    },

    {
        itemName: "Chocolate",
        rowOrder: 36,
        quantityFor1: "1",
        quantityFor2: "1",
        quantityFor3: "1",
        quantityFor4: "1",
        quantityFor5: "2",
        quantityFor6: "2",
        quantityFor7: "2",
        quantityFor8: "2",
        quantityFor9: "2",
        quantityFor10: "2",
    },

    {
        itemName: "Biscuits",
        rowOrder: 37,
        quantityFor1: "1",
        quantityFor2: "1",
        quantityFor3: "2",
        quantityFor4: "2",
        quantityFor5: "2",
        quantityFor6: "3",
        quantityFor7: "3",
        quantityFor8: "3",
        quantityFor9: "4",
        quantityFor10: "4",
    },

    {
        itemName: "Sanitary Pads",
        rowOrder: 38,
        quantityFor2: "1 pack per person",
        notesFor2: "as required. Add panty liners as well.",
        quantityFor3: "1 pack per person",
        notesFor3: "as required. Add panty liners as well.",
        quantityFor4: "1 pack per person",
        notesFor4: "as required. Add panty liners as well.",
        quantityFor5: "1 pack per person",
        notesFor5: "as required. Add panty liners as well.",
        quantityFor6: "1 pack per person",
        notesFor6: "as required. Add panty liners as well.",
        quantityFor7: "1 pack per person",
        notesFor7: "as required. Add panty liners as well.",
        quantityFor8: "1 pack per person",
        notesFor8: "as required. Add panty liners as well.",
        quantityFor9: "1 pack per person",
        notesFor9: "as required. Add panty liners as well.",
        quantityFor10: "1 pack per person",
        notesFor10: "as required. Add panty liners as well.",
    },

    {
        itemName: "Tampons",
        rowOrder: 39,
        quantityFor2: "2 packs per person",
        notesFor2: "If required. Add panty liners as well.",
        quantityFor3: "2 packs per person",
        notesFor3: "If required. Add panty liners as well.",
        quantityFor4: "2 packs per person",
        notesFor4: "If required. Add panty liners as well.",
        quantityFor5: "2 packs per person",
        notesFor5: "If required. Add panty liners as well.",
        quantityFor6: "2 packs per person",
        notesFor6: "If required. Add panty liners as well.",
        quantityFor7: "2 packs per person",
        notesFor7: "If required. Add panty liners as well.",
        quantityFor8: "2 packs per person",
        notesFor8: "If required. Add panty liners as well.",
        quantityFor9: "2 packs per person",
        notesFor9: "If required. Add panty liners as well.",
        quantityFor10: "2 packs per person",
        notesFor10: "If required. Add panty liners as well.",
    },

    {
        itemName: "Toilet Roll",
        rowOrder: 40,
        quantityFor1: "1",
        quantityFor2: "1",
        quantityFor3: "2",
        quantityFor4: "2",
        quantityFor5: "2",
        quantityFor6: "3",
        quantityFor7: "3",
        quantityFor8: "3",
        quantityFor9: "3",
        quantityFor10: "3",
    },

    {
        itemName: "Easter choc treat",
        rowOrder: 41,
        quantityFor1: "1",
        notesFor1: "Find at end of packing tables",
        quantityFor2: "2",
        notesFor2: "Find at end of packing tables",
        quantityFor3: "3",
        notesFor3: "Find at end of packing tables",
        quantityFor4: "4",
        notesFor4: "Find at end of packing tables",
        quantityFor5: "5",
        notesFor5: "Find at end of packing tables",
        quantityFor6: "6",
        notesFor6: "Find at end of packing tables",
        quantityFor7: "7",
        notesFor7: "Find at end of packing tables",
        quantityFor8: "8",
        notesFor8: "Find at end of packing tables",
        quantityFor9: "9",
        notesFor9: "Find at end of packing tables",
        quantityFor10: "10",
        notesFor10: "Find at end of packing tables",
    },
];

export const listsSeedRequired: SnapletListRequired[] = listsSeed.map((list) =>
    snapletListToRequired(list)
);
