import { randomUUID } from "crypto";
import { BatchGridDisplayRow } from "./BatchParcelDataGrid";

const mockData: BatchGridDisplayRow[] = [
    {
        id: 0,
        rowName: 0,
        fullName: "",
        phoneNumber: "",
        address: "",
        adults: null,
        children: null,
        listType: "",
        dietaryRequirements: "",
        feminineProducts: "",
        babyProducts: "",
        petFood: "",
        otherItems: "",
        deliveryInstructions: "",
        extraInformation: "",
        attentionFlag: "",
        signpostingCall: "",
        notes: "",
        voucherNumber: "",
        packingDate: "",
        packingSlot: "",
        shippingMethod: "",
        collectionInfo: "",
    },
    {
        id: crypto.randomUUID(),
        rowName: 1,
        fullName: "John Doe",
        phoneNumber: "0123456789",
        address: "123 Main Street, Anytown, USA",
        adults: 3,
        children: 1,
        listType: "Hotel",
        dietaryRequirements: "Vegan",
        feminineProducts: "No",
        babyProducts: "Yes",
        petFood: "No",
        otherItems: "None",
        deliveryInstructions: "Leave at 10 am",
        extraInformation: "No special requests",
        attentionFlag: "Yes",
        signpostingCall: "No",
        notes: "None",
        voucherNumber: "123456789",
        packingDate: "2022-01-01",
        packingSlot: "Morning",
        shippingMethod: "Collection",
        collectionInfo: "Test centre, date, slot",
    },
    {
        id: crypto.randomUUID(),
        rowName: 2,
        fullName: "Jane Smiths",
        phoneNumber: "9876543210",
        address: "456 Elm Street, Anytown, USA",
        adults: 2,
        children: 1,
        listType: "Regular",
        dietaryRequirements: "Gluten-free",
        feminineProducts: "Yes",
        babyProducts: "No",
        petFood: "Yes",
        otherItems: "None",
        deliveryInstructions: "Leave at 12 pm",
        extraInformation: "No special requests",
        attentionFlag: "No",
        signpostingCall: "Yes",
        notes: "None",
        voucherNumber: "987654321",
        packingDate: "2022-01-02",
        packingSlot: "Afternoon",
        shippingMethod: "Delivery",
        collectionInfo: "Test centre, date, slot",
    },
];

export default mockData;
