import { BatchTableDataState } from "./BatchDataRow";
import { BatchGridDisplayRow } from "./BatchParcelDataGrid";

export const mockDisplayData: BatchGridDisplayRow[] = [
    {
        id: 0,
        rowName: 0,
        fullName: "",
        phoneNumber: "",
        address: "",
        adults: null,
        children: null,
        listType: "",
        dietaryRequirements: "",
        feminineProducts: "",
        babyProducts: "",
        petFood: "",
        otherItems: "",
        deliveryInstructions: "",
        extraInformation: "",
        attentionFlag: "",
        signpostingCall: "",
        notes: "",
        voucherNumber: "",
        packingDate: "",
        packingSlot: "",
        shippingMethod: "",
        collectionInfo: "",
    },
    {
        id: 1,
        rowName: 1,
        fullName: "John Doe",
        phoneNumber: "0123456789",
        address: "123 Main Street, Anytown, USA",
        adults: 3,
        children: 1,
        listType: "Hotel",
        dietaryRequirements: "Vegan",
        feminineProducts: "No",
        babyProducts: "Yes",
        petFood: "No",
        otherItems: "None",
        deliveryInstructions: "Leave at 10 am",
        extraInformation: "No special requests",
        attentionFlag: "Yes",
        signpostingCall: "No",
        notes: "None",
        voucherNumber: "123456789",
        packingDate: "2022-01-01",
        packingSlot: "Morning",
        shippingMethod: "Collection",
        collectionInfo: "Test centre, date, slot",
    },
    {
        id: 2,
        rowName: 2,
        fullName: "Jane Smiths",
        phoneNumber: "9876543210",
        address: "456 Elm Street, Anytown, USA",
        adults: 2,
        children: 1,
        listType: "Regular",
        dietaryRequirements: "Gluten-free",
        feminineProducts: "Yes",
        babyProducts: "No",
        petFood: "Yes",
        otherItems: "None",
        deliveryInstructions: "Leave at 12 pm",
        extraInformation: "No special requests",
        attentionFlag: "No",
        signpostingCall: "Yes",
        notes: "None",
        voucherNumber: "987654321",
        packingDate: "2022-01-02",
        packingSlot: "Afternoon",
        shippingMethod: "Delivery",
        collectionInfo: "Test centre, date, slot",
    },
];

export const mockTableDataState: BatchTableDataState = {
    overrideDataRow: {
        data: {
            client: {
                fullName: null,
                phoneNumber: null,
                address: null,
                adultInfo: null,
                childrenInfo: null,
                listType: null,
                dietaryRequirements: null,
                feminineProducts: null,
                babyProducts: null,
                nappySize: null,
                petFood: null,
                otherItems: null,
                deliveryInstructions: null,
                extraInformation: null,
                attentionFlag: null,
                signpostingCall: null,
                notes: null,
            },
            parcel: {
                voucherNumber: null,
                packingDate: null,
                packingSlot: null,
                shippingMethod: null,
                collectionInfo: null,
            },
        },
    },
    batchDataRows: [
        {
            id: 1,
            clientId: "1",
            data: {
                client: {
                    fullName: "John Doe",
                    phoneNumber: "0123456789",
                    address: {
                        addressLine1: "123 Main St",
                        addressLine2: null,
                        addressTown: "Anytown",
                        addressCounty: "USA",
                        addressPostcode: "12345",
                    },
                    adultInfo: {
                        adults: [],
                        numberOfAdults: 0,
                    },
                    childrenInfo: {
                        children: [],
                        numberOfChildren: 0,
                    },
                    listType: "hotel",
                    dietaryRequirements: { vegan: true },
                    feminineProducts: { tampons: false, pads: false },
                    babyProducts: null,
                    nappySize: null,
                    petFood: { cat: false, dog: false },
                    otherItems: { toothpaste: false, toothbrush: false },
                    deliveryInstructions: "Leave at 10 am",
                    extraInformation: "No special requests",
                    attentionFlag: true,
                    signpostingCall: false,
                    notes: null,
                },
                clientReadOnly: false,
                parcel: null,
            },
        },
        {
            id: 2,
            clientId: "2",
            data: {
                client: {
                    fullName: "Jane Smiths",
                    phoneNumber: "9876543210",
                    address: {
                        addressLine1: "456 Elm St",
                        addressLine2: null,
                        addressTown: "Anytown",
                        addressCounty: "USA",
                        addressPostcode: "54321",
                    },
                    adultInfo: {
                        adults: [],
                        numberOfAdults: 0,
                    },
                    childrenInfo: {
                        children: [],
                        numberOfChildren: 0,
                    },
                    listType: "regular",
                    dietaryRequirements: { "gluten-free": true },
                    feminineProducts: { tampons: true, pads: false },
                    babyProducts: false,
                    nappySize: null,
                    petFood: { cat: true, dog: false },
                    otherItems: { toothpaste: false, toothbrush: false },
                    deliveryInstructions: "Leave at 12 pm",
                    extraInformation: "No special requests",
                    attentionFlag: false,
                    signpostingCall: true,
                    notes: null,
                },
                clientReadOnly: false,
                parcel: null,
            },
        },
    ],
};

// export mockExistingClientRow :
