alter table "public"."wiki" drop constraint "wiki_order_key";

alter table "public"."wiki" drop constraint "wiki_pkey";

drop index if exists "public"."wiki_order_key";

drop index if exists "public"."wiki_pkey";

alter table "public"."wiki" drop column "order";

alter table "public"."wiki" add column "row_order" bigint generated by default as identity not null;

alter table "public"."wiki" add column "wiki_key" uuid not null default gen_random_uuid();

CREATE UNIQUE INDEX wiki_order_key ON public.wiki USING btree (row_order);

CREATE UNIQUE INDEX wiki_pkey ON public.wiki USING btree (wiki_key);

alter table "public"."wiki" add constraint "wiki_pkey" PRIMARY KEY using index "wiki_pkey";

alter table "public"."wiki" add constraint "wiki_order_key" UNIQUE using index "wiki_order_key";


