alter table "public"."wiki" drop constraint "wiki_pkey";

drop index if exists "public"."wiki_pkey";

alter table "public"."clients" add column "default_list" list_type not null default 'regular'::list_type;

alter table "public"."lists" add column "list_type" list_type not null default 'regular'::list_type;

alter table "public"."parcels" add column "list_type" list_type not null default 'regular'::list_type;

alter table "public"."wiki" alter column "order" drop default;

alter table "public"."wiki" alter column "order" add generated by default as identity;

CREATE UNIQUE INDEX wiki_order_key ON public.wiki USING btree ("order");

CREATE UNIQUE INDEX wiki_pkey ON public.wiki USING btree (title, "order");

alter table "public"."wiki" add constraint "wiki_pkey" PRIMARY KEY using index "wiki_pkey";

alter table "public"."wiki" add constraint "wiki_order_key" UNIQUE using index "wiki_order_key";


